export const BASE_URL = 'https://edgeemu.net';
export const URLS = [
    // 'https://edgeemu.net/browse-cpc.htm',
    // 'https://edgeemu.net/browse-2600.htm',
    // 'https://edgeemu.net/browse-5200.htm',
    // 'https://edgeemu.net/browse-7800.htm',
    // 'https://edgeemu.net/browse-jaguar.htm',
    // 'https://edgeemu.net/browse-lynx.htm',
    // 'https://edgeemu.net/browse-c64.htm',
    // 'https://edgeemu.net/browse-amiga.htm',
    // 'https://edgeemu.net/browse-wsx.htm',
    // 'https://edgeemu.net/browse-msx.htm',
    // 'https://edgeemu.net/browse-pce.htm',
    // 'https://edgeemu.net/browse-pcecd.htm',
    // 'https://edgeemu.net/browse-n64.htm',
    // 'https://edgeemu.net/browse-nds.htm',
    // 'https://edgeemu.net/browse-nes.htm',
    // 'https://edgeemu.net/browse-gba.htm',
    // 'https://edgeemu.net/browse-gbc.htm',
    // 'https://edgeemu.net/browse-gc.htm',
    // 'https://edgeemu.net/browse-snes.htm',
    // 'https://edgeemu.net/browse-vb.htm',
    // 'https://edgeemu.net/browse-3do.htm',
    // 'https://edgeemu.net/browse-cdi.htm',
    // 'https://edgeemu.net/browse-32x.htm',
    // 'https://edgeemu.net/browse-segacd.htm',
    // 'https://edgeemu.net/browse-dc.htm',
    // 'https://edgeemu.net/browse-gg.htm',
    // 'https://edgeemu.net/browse-md.htm',
    // 'https://edgeemu.net/browse-sms.htm',
    // 'https://edgeemu.net/browse-saturn.htm',
    // 'https://edgeemu.net/browse-ngpc.htm',
    // 'https://edgeemu.net/browse-ngcd.htm',
];